GET http://localhost:3000/players/

###
GET http://localhost:3000/players/2/

###
PUT  http://localhost:3000/players/2/
Content-Type: application/json

{
  "playerName": "Raju"
}

###
GET http://localhost:3000/matches/18/

###
GET http://localhost:3000/players/9/matches

###
GET http://localhost:3000/matches/3/players

###
GET http://localhost:3000/players/3/playerScores
